
// Get all contacts
GET http://localhost:3000/armadas

###

GET https://amy-baker-armada.herokuapp.com/armadas

###
// Get Contacts by ID
GET http://localhost:3000/armadas/629ba54874ab17889fdc621d

###

GET https://amy-baker-armada.herokuapp.com/armadas/61a921f6028954d4f0319f76


#####
// Add Contact
POST http://localhost:3000/armadas HTTP/1.1
Content-Type : application/json
  
  {
      
      "shipName": "H.M.S. dog",
      "shipType": "Sailboat",
      "cannons": "10",
      "sails": "23",
      "crew": "5",
      "damage":"2"
    
  }


####
POST https://amy-baker-armada.herokuapp.com/armadas HTTP/1.1
Content-Type : application/json
  
  {
      "shipName": "H.M.S. Beagle",
      "shipType": "Pirate",
      "cannons": "10",
      "sails": "23",
      "crew": "5",
      "damage":"2"
  }



#####
//Modify Contact
PUT http://localhost:3000/armadas/62abfe963c632d3b762ce7df HTTP/1.1
Content-Type:application/json

  {
      "shipName": "H.M.S. Pug",
      "shipType": "Tug Boat",
      "cannons": "0",
      "sails": "2",
      "crew": "1",
      "damage":"0"
  }


####  
PUT https://amy-baker-armada.herokuapp.com/armadas/629ba56528a08a0c1180f925 HTTP/1.1
Content-Type:application/json

  {
    "shipName": "H.M.S. Beagle",
    "shipType": "Pirate",
    "cannons": "10",
    "sails": "23",
    "crew": "5",
    "damage":"2"
  }


####
DELETE http://localhost:3000/armadas/62a7dd9ea8a2a0fa7d57edd1 HTTP/1.1
Content-Type:application/json

####
DELETE https://amy-baker-armada.herokuapp.com/armadas/62899d7a6896f005250e1902 HTTP/1.1
Content-Type:application/json


