
// Get all contacts
GET http://localhost:3000/users

###

GET https://amy-baker-armada.herokuapp.com/users

###
// Get Contacts by ID
GET http://localhost:3000/users/61a921f6028954d4f0319f76

###

GET https://amy-baker-armada.herokuapp.com/users/61a921f6028954d4f0319f76


#####
// Add Contact
POST http://localhost:3000/users HTTP/1.1
Content-Type : application/json
  
  {
      "firstName":"testing",
    "lastName":"Validation",
    "email":"bestCat@cat.com",
    "password":"12345"
    
  }


####
POST https://amy-baker-armada.herokuapp.com/users HTTP/1.1
Content-Type : application/json
  
  {
      "firstName":"testing from heroku",
    "lastName":"validation",
    "email":"bake@amy.com",
    "password":"12345"
  }



#####
//Modify Contact
PUT http://localhost:3000/users/629ba56528a08a0c1180f925 HTTP/1.1
Content-Type:application/json

  {
      "firstName":"modified",
    "lastName":"testingValidation",
    "email":"bestCat@cat.com",
    "password":"12345"
  }


####  
PUT https://amy-baker-armada.herokuapp.com/users/629ba56528a08a0c1180f925 HTTP/1.1
Content-Type:application/json

  {
      "firstName":"modified from Heroku",
    "lastName":"Contact",
    "email":"bestCat@cat.com",
    "password":"12345"
  }


####
DELETE http://localhost:3000/users/62899ca66896f005250e1900 HTTP/1.1
Content-Type:application/json

####
DELETE https://amy-baker-armada.herokuapp.com/users/62899d7a6896f005250e1902 HTTP/1.1
Content-Type:application/json


